"""
FIPS Country Code to Country Name Mapping
Maps 2-character FIPS codes to full country names
"""

COUNTRY_CODES = {
    'AF': 'Afghanistan',
    'AX': 'Akrotiri',
    'AL': 'Albania',
    'AG': 'Algeria',
    'AQ': 'American Samoa',
    'AN': 'Andorra',
    'AO': 'Angola',
    'AV': 'Anguilla',
    'AY': 'Antarctica',
    'AC': 'Antigua and Barbuda',
    'AR': 'Argentina',
    'AM': 'Armenia',
    'AA': 'Aruba',
    'AT': 'Ashmore and Cartier Islands',
    'AS': 'Australia',
    'AU': 'Austria',
    'AJ': 'Azerbaijan',
    'BF': 'Bahamas',
    'BA': 'Bahrain',
    'FQ': 'Baker Island',
    'BG': 'Bangladesh',
    'BB': 'Barbados',
    'BO': 'Belarus',
    'BE': 'Belgium',
    'BH': 'Belize',
    'BN': 'Benin',
    'BD': 'Bermuda',
    'BT': 'Bhutan',
    'BL': 'Bolivia',
    'BK': 'Bosnia and Herzegovina',
    'BC': 'Botswana',
    'BV': 'Bouvet Island',
    'BR': 'Brazil',
    'IO': 'British Indian Ocean Territory',
    'VI': 'British Virgin Islands',
    'BX': 'Brunei',
    'BU': 'Bulgaria',
    'UV': 'Burkina Faso',
    'BM': 'Burma (Myanmar)',
    'BY': 'Burundi',
    'CB': 'Cambodia',
    'CM': 'Cameroon',
    'CA': 'Canada',
    'CV': 'Cape Verde',
    'CJ': 'Cayman Islands',
    'CT': 'Central African Republic',
    'CD': 'Chad',
    'CI': 'Chile',
    'CH': 'China',
    'KT': 'Christmas Island',
    'IP': 'Clipperton Island',
    'CK': 'Cocos (Keeling) Islands',
    'CO': 'Colombia',
    'CN': 'Comoros',
    'CF': 'Congo (Brazzaville)',
    'CG': 'Congo (Kinshasa)',
    'CW': 'Cook Islands',
    'CR': 'Coral Sea Islands',
    'CS': 'Costa Rica',
    'IV': 'Côte d\'Ivoire',
    'HR': 'Croatia',
    'CU': 'Cuba',
    'UC': 'Curaçao',
    'CY': 'Cyprus',
    'EZ': 'Czech Republic',
    'DA': 'Denmark',
    'DX': 'Dhekelia',
    'DJ': 'Djibouti',
    'DO': 'Dominica',
    'DR': 'Dominican Republic',
    'EC': 'Ecuador',
    'EG': 'Egypt',
    'ES': 'El Salvador',
    'EK': 'Equatorial Guinea',
    'ER': 'Eritrea',
    'EN': 'Estonia',
    'ET': 'Ethiopia',
    'FK': 'Falkland Islands',
    'FO': 'Faroe Islands',
    'FJ': 'Fiji',
    'FI': 'Finland',
    'FR': 'France',
    'FP': 'French Polynesia',
    'FS': 'French Southern and Antarctic Lands',
    'GB': 'Gabon',
    'GA': 'Gambia',
    'GG': 'Georgia',
    'GM': 'Germany',
    'GH': 'Ghana',
    'GI': 'Gibraltar',
    'GR': 'Greece',
    'GL': 'Greenland',
    'GJ': 'Grenada',
    'GQ': 'Guam',
    'GT': 'Guatemala',
    'GK': 'Guernsey',
    'GV': 'Guinea',
    'PU': 'Guinea-Bissau',
    'GY': 'Guyana',
    'HA': 'Haiti',
    'HM': 'Heard Island and McDonald Islands',
    'VT': 'Holy See (Vatican City)',
    'HO': 'Honduras',
    'HK': 'Hong Kong',
    'HQ': 'Howland Island',
    'HU': 'Hungary',
    'IC': 'Iceland',
    'IN': 'India',
    'ID': 'Indonesia',
    'IR': 'Iran',
    'IZ': 'Iraq',
    'EI': 'Ireland',
    'IM': 'Isle of Man',
    'IS': 'Israel',
    'IT': 'Italy',
    'JM': 'Jamaica',
    'JN': 'Jan Mayen',
    'JA': 'Japan',
    'DQ': 'Jarvis Island',
    'JE': 'Jersey',
    'JQ': 'Johnston Atoll',
    'JO': 'Jordan',
    'KZ': 'Kazakhstan',
    'KE': 'Kenya',
    'KQ': 'Kingman Reef',
    'KR': 'Kiribati',
    'KN': 'Korea, North',
    'KS': 'Korea, South',
    'KV': 'Kosovo',
    'KU': 'Kuwait',
    'KG': 'Kyrgyzstan',
    'LA': 'Laos',
    'LG': 'Latvia',
    'LE': 'Lebanon',
    'LT': 'Lesotho',
    'LI': 'Liberia',
    'LY': 'Libya',
    'LS': 'Liechtenstein',
    'LH': 'Lithuania',
    'LU': 'Luxembourg',
    'MC': 'Macau',
    'MK': 'Macedonia',
    'MA': 'Madagascar',
    'MI': 'Malawi',
    'MY': 'Malaysia',
    'MV': 'Maldives',
    'ML': 'Mali',
    'MT': 'Malta',
    'RM': 'Marshall Islands',
    'MR': 'Mauritania',
    'MP': 'Mauritius',
    'MX': 'Mexico',
    'FM': 'Micronesia',
    'MQ': 'Midway Islands',
    'MD': 'Moldova',
    'MN': 'Monaco',
    'MG': 'Mongolia',
    'MJ': 'Montenegro',
    'MH': 'Montserrat',
    'MO': 'Morocco',
    'MZ': 'Mozambique',
    'WA': 'Namibia',
    'NR': 'Nauru',
    'BQ': 'Navassa Island',
    'NP': 'Nepal',
    'NL': 'Netherlands',
    'NC': 'New Caledonia',
    'NZ': 'New Zealand',
    'NU': 'Nicaragua',
    'NG': 'Niger',
    'NI': 'Nigeria',
    'NE': 'Niue',
    'NF': 'Norfolk Island',
    'CQ': 'Northern Mariana Islands',
    'NO': 'Norway',
    'MU': 'Oman',
    'PK': 'Pakistan',
    'PS': 'Palau',
    'LQ': 'Palmyra Atoll',
    'PM': 'Panama',
    'PP': 'Papua New Guinea',
    'PF': 'Paracel Islands',
    'PA': 'Paraguay',
    'PE': 'Peru',
    'RP': 'Philippines',
    'PC': 'Pitcairn Islands',
    'PL': 'Poland',
    'PO': 'Portugal',
    'RQ': 'Puerto Rico',
    'QA': 'Qatar',
    'RO': 'Romania',
    'RS': 'Russia',
    'RW': 'Rwanda',
    'TB': 'Saint Barthélemy',
    'SH': 'Saint Helena',
    'SC': 'Saint Kitts and Nevis',
    'ST': 'Saint Lucia',
    'RN': 'Saint Martin',
    'SB': 'Saint Pierre and Miquelon',
    'VC': 'Saint Vincent and the Grenadines',
    'WS': 'Samoa',
    'SM': 'San Marino',
    'TP': 'São Tomé and Príncipe',
    'SA': 'Saudi Arabia',
    'SG': 'Senegal',
    'RI': 'Serbia',
    'SE': 'Seychelles',
    'SL': 'Sierra Leone',
    'SN': 'Singapore',
    'NN': 'Sint Maarten',
    'LO': 'Slovakia',
    'SI': 'Slovenia',
    'BP': 'Solomon Islands',
    'SO': 'Somalia',
    'SF': 'South Africa',
    'SX': 'South Georgia and South Sandwich Islands',
    'OD': 'South Sudan',
    'SP': 'Spain',
    'PG': 'Spratly Islands',
    'CE': 'Sri Lanka',
    'SU': 'Sudan',
    'NS': 'Suriname',
    'SV': 'Svalbard',
    'WZ': 'Swaziland',
    'SW': 'Sweden',
    'SZ': 'Switzerland',
    'SY': 'Syria',
    'TW': 'Taiwan',
    'TI': 'Tajikistan',
    'TZ': 'Tanzania',
    'TH': 'Thailand',
    'TT': 'Timor-Leste',
    'TO': 'Togo',
    'TL': 'Tokelau',
    'TN': 'Tonga',
    'TD': 'Trinidad and Tobago',
    'TS': 'Tunisia',
    'TU': 'Turkey',
    'TX': 'Turkmenistan',
    'TK': 'Turks and Caicos Islands',
    'TV': 'Tuvalu',
    'UG': 'Uganda',
    'UP': 'Ukraine',
    'AE': 'United Arab Emirates',
    'UK': 'United Kingdom',
    'US': 'United States',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'NH': 'Vanuatu',
    'VE': 'Venezuela',
    'VM': 'Vietnam',
    'VQ': 'Virgin Islands (US)',
    'WQ': 'Wake Island',
    'WF': 'Wallis and Futuna',
    'WE': 'West Bank',
    'WI': 'Western Sahara',
    'YM': 'Yemen',
    'ZA': 'Zambia',
    'ZI': 'Zimbabwe',
}

def get_country_name(code):
    """Get country name from FIPS code."""
    return COUNTRY_CODES.get(code, code)

def get_country_code(name):
    """Get FIPS code from country name."""
    for code, country_name in COUNTRY_CODES.items():
        if country_name == name:
            return code
    return name

def get_all_country_names():
    """Get list of all country names sorted alphabetically."""
    return sorted(COUNTRY_CODES.values())

def get_country_name_to_code_dict():
    """Get dictionary mapping country names to codes."""
    return {name: code for code, name in COUNTRY_CODES.items()}

